name: Build Web App

on:
    pull_request:
        branches:
            - master
        paths:
            - "packages/web/**"
            - "packages/quicktype-core/**"
            - "packages/quicktype-graphql-input/**"
            - ".github/workflows/build-web.yml"

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version-file: .nvmrc
                  cache: npm
            - run: npm ci
            - name: Build engine packages for web
              run: |
                  npm run build --workspace=packages/quicktype-core
                  npm run build --workspace=packages/quicktype-graphql-input
            - run: APP_VERSION=ci bun run build
              working-directory: packages/web
